config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :events # ルーティングをまとめて設定(index、new、create、show、edit、update、destroyアクションに対するルーティングを設定してくれる。)
  get "/" => 'events#index' # トップページの設定にはrootが用いられる
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  validate :end_date_after_start_date

  private

  def end_date_after_start_date #カレンダーの終了日を開始日以前で設定出来なくする

    if end_date.present? && end_date <= start_date
      errors.add(:end_date, "は開始日より後の日付でなければなりません")
    end
    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index #一覧表示画面
    @events = Event.all
  end
  
  def new #新規登録画面
    @event = Event.new
  end
  
  def show #詳細表示画面
    @event = Event.find(params[:id])
  end
  
  def edit #編集画面
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      
      flash[:notice] = 'イベントが作成されました'
      redirect_to events_path
    else
      render :new, alert: '保存に失敗しました'
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      #更新に成功した時の処理

      flash[:notice] = 'イベントが更新されました'
      redirect_to events_path, notice: 'イベントが更新されました'

    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    flash[:notice_destroy] = "スケジュールを削除しました"
    redirect_to events_path
  end


  def index # コントローラーで現在の日付を取得する
    @events = Event.all
    @today = Date.today
  end

  private

  def event_params
    params.require(:event).permit(:title, :start_date, :end_date, :is_all_day, :memo)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index #一覧表示画面
    @events = Event.all
  end
  
  def new #新規登録画面
    @event = Event.new
  end
  
  def show #詳細表示画面
    @event = Event.find(params[:id])
  end
  
  def edit #編集画面
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to event_path(@event), notice: 'イベントが作成されました'
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :start_date, :end_date, :all_day, :memo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/events/edit.html.erb
<h3>予定の編集</h3>

<%= form_with model: @event do |f| %>
  <table>
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>

    <tr>
      <th><%= f.label :start_date, "開始日" %></th>
      <td><%= f.date_field :start_date %></td>
    </tr>

    <tr>
      <th><%= f.label :end_date, "終了日" %></th>
      <td><%= f.date_field :end_date %></td>
    </tr>

    <tr>
      <th><%= f.label :is_all_day ,"終日の場合はチェックを入れます" %></th>
      <td><%= f.check_box :is_all_day %></td>
    </tr>

    <tr>
      <th><%= f.label :memo ,"スケジュールメモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "編集を完了する"%></li>
      <li><%= link_to "キャンセル", events_path %></li>
    </ul>
  </div>

<% if flash[:notice_no_update] %>
  <p class="notice"><%= flash[:notice_no_update] %></p>
<% end %>

<%= render "shared/error", obj: @event %> 
<% end %>

<%= render partial: "shared/error", locals: { obj: @event } %>

app/views/events/index.html.erb
<div class="index">

<h2>予定一覧</h2>

<div class="index1">
  <%= link_to new_event_path, class: "btn btn-primary btn-sm" do %>
    新規追加
  <% end %>
</div>


<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日時</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
      
        <td><%= event.id %></td>
        <td><%= event.title %></td>
        <td><%= event.start_date %></td>
        <td><%= event.end_date %></td>

        <td class="all-day-event">
        <% if event.is_all_day %>
          ⚪︎
        <% end %>
        </td>

        <td><%= event.created_at.strftime("%Y/%m/%d %H:%M") %></td><%# 日時の設定 %>
      
        <td><%= link_to "詳細", event_path(event) %></td>
        <!-- 詳細ページへのリンク -->
        <td><%= link_to "編集", edit_event_path(event) %></td>
        <!-- 編集ページへのリンク -->
        <td><%= link_to "削除", event_path(event), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "item-destroy" %></td>

      </tr>
    <% end %>
  </tbody>
</table>
  
  <div class="info">
    <p>予定合計: <%= @events.count %>件</p>
    <p>本日の日付: <%= @today.strftime("%Y/%m/%d") %></p>
</div>

</div>

app/views/events/new.html.erb
<h3>予定の新規追加</h3>

<div class="nwetask">
<%= form_with model: @event, url: events_path do |f| %>
  <table>
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>

    <tr>
      <th><%= f.label :start_date ,"開始日" %></th>
      <td><%= f.date_field :start_date %></td>
    </tr>

    <tr>
      <th><%= f.label :end_date ,"終了日" %></th>
      <td><%= f.date_field :end_date %></td>
    </tr>

    <tr>
      <th><%= f.label :is_all_day ,"終日の場合はチェックを入れます" %></th>
      <td><%= f.check_box :is_all_day %></td>
    </tr>

    <tr>
      <th><%= f.label :memo ,"スケジュールメモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "登録完了する"%></li>
      <li><%= link_to "キャンセル", events_path %></li>
    </ul>
  </div>
<% end %>
</div>

app/views/events/show.html.erb
<div class="event-details">



<div class="back-index">
  <%= link_to '← 一覧に戻る', events_path %>
</div>

  <div class="title-with-edit">
    <h1><%= @event.title %></h1>
    <%= link_to '編集', edit_event_path(@event) %>
  </div>
  
  <p>開始日: <%= @event.start_date %></p>
  <p>終了日: <%= @event.end_date %></p>
  <p>終日: <%= @event.is_all_day ? 'はい' : 'いいえ' %></p>
  <p>スケジュールメモ: <%= @event.memo %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'rails-ujs' %>

  </head>

  <body>
    <%= yield %>
    <header>
      <div class="partial">
      <h4>スケジュール管理アプリ</h4>
      </div>
    </header>
  </body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(obj.errors.count, "error") %> prohibited this record from being saved:</h2>

    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/index.html.erb
<h3>予定一覧</h3>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日時</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |task| %>
      <tr>
      <td><%= task.id %></td>
      <td><%= task.title %></td>
      <td><%= task.start_date %></td>
      <td><%= task.end_date %></td>
      <td><%= task.all_day %></td>
      <td><%= task.updated_at %></td>

        <td></td>
        <td></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "新規追加", :new_task %></p>

app/views/tasks/new.html.erb
<h3>予定の新規追加</h3>

<%= form_with model: @event, url: tasks_path do |f| %>
  <table>
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>

    <tr>
      <th><%= f.label :start_datetime ,"開始日" %></th>
      <td><%= f.datetime_field :start_datetime %></td>
    </tr>

    <tr>
      <th><%= f.label :end_datetime ,"終了日" %></th>
      <td><%= f.datetime_field :end_datetime %></td>
    </tr>

    <tr>
      <th><%= f.label :is_all_day ,"終日の場合はチェックを入れます" %></th>
      <td><%= f.check_box :is_all_day %></td>
    </tr>

    <tr>
      <th><%= f.label :memo ,"スケジュールメモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "登録完了する"%></li>
      <li><%= link_to "キャンセル", tasks_path %></li>
    </ul>
  </div>
<% end %>